---
title: "Tuần_7_phuongphaplamgiamsochieudulieu"
author: "VuTienDat"
date: "2025-10-24"
output: html_document
---

### Phương pháp làm giảm số chiều dữ liệu

```{r}
inverst = read.table("D:\\hocki-1-nam-3-toantin\\hocki-1-nam-3-toantin\\phan_tich_thong_ke_nhieu_chieu\\Dat\\Học\\investment.txt", header = T)

head(inverst)

rownames(inverst)  = inverst$Manager
inverst = inverst[, -1]
colnames(inverst) = c("S.US", "S.U.US")




#a. Xét trên tappj dữ liệu:
pc = princomp(inverst) #== princomp(inverst, cor = false)

# xem xét với cov = 1/n * sum((y - y_)^2)
# computes eigenvalues and eigenvectors and presents thế in a suitable format
s = summary(pc)
s #sd = standard deviations = căn(lamda1) >= căn(lamda2) >= .... >= căn (lamda8) với lamda_i là giá trị riêng của ma trận hiệp phương sai 
s$sdev # sD(y_i) gần đúng == căn(lamda_i)
# Tính căn(lamda_i)
sqrt(eigen(cov(invest))$values) # Căn lamda_i

# invest - matrix(rep(colMeans9invest), nrow(invest)), nrow = nrow(invest), byrom = T,
# princomp(cov(invenst - matrix(rep(colmeans(invenst), nrow(invest)), nrow = neow(invest)))

# Xét trên ma trận hiệp pương sai của tập dữ liệu: cov = 1 / (n-1) * sum(y - y_h)
pcacov = princomp(covmat = cov(invest))
summary(pcacov)
# Đưa ra hiệp hupwng sai của các thành phần chính và so sánh với giá trị riêng của ma trận hiệp phương sai của X.

# Nhận xét từng thành phần chính:


```

```{r}
#biplot
pc = princomp(invest)
bipblot(pc, col = c(2,4), cex = c(.5, 1.25),
        xlim = c(-.45, .45),
        xlab = "first principal component",
        ylab = "second principal component",
        main = "biblot for investment allocaiton")


```
