---
title: "Exercise_week1"
author: "Nguyễn Hiền Trang"
date: "2025-09-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Câu 1

```{r}
X = c(1, 2, 3, 4, 5, 6, 7, 8, 9)
Y = c(1.5, 2.3, 3.2, 4.6, 5.4, 6.6, 7.6, 8.6, 9.1)

#aTính độ dài 2 vector,tính tổng, hiệu, tích, chuẩn của 2 vector.
len_X = sqrt(sum(X^2))
len_Y = sqrt(sum(Y^2))
print(paste("Độ dài 2 vector là", len_X, "and", len_Y))

sum = X + Y
print(paste(sum))

diff = X - Y
print(diff)

prod = X * Y
print(prod)

norm_X = norm(as.matrix(X), type = "2")
print(norm_X)
norm_Y = norm(as.matrix(Y), type = "2")
print(norm_Y)

#b.Trích ra phần tử thứ 1,3,5 trong vector X, và phần tử không phải thứ 4,5,6 trong vector Y.
X[c(1,3,5)]
Y[c(4,5,6)]
X[length(X)] <- prod(X[-length(X)])   # phần tử cuối = tích các phần tử còn lại
Y[2] <- 99
Y[7] <- 199
X
Y
Y_round <- round(Y, 0)
Y_round

#c. Thay giá trị phần tử cuối cùng của X bởi tích các phần tử còn lại. Thay giá trị của phần tử thứ 2 và thứ 7 của Y bởi 99 và 199.
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
