---
title: "Tuần 4"
author: "VuTienDat"
date: "2025-09-26"
output: html_document
---

# Study4: Hồi quy tuyến tính

```{r}
# Xem xét mối tương quan tuyến tính giữa 2 biến 
# medv và lstat của bộ dữ liệu Boston
install.packages("MASS")
library(MASS)
data("Boston")
View(Boston)

# Trích xuất các cột dữ liệu của thư viện Boston
attach(Boston) # Tách tất cả các cột, có thể dùng trực tiếp mà không cần $
lstat
#Xem xét mối tương quan giữa 2 bien
#medv va lstat của bộ dữ liệu

# Hệ số tương quan mẫu r giữa medv và lstat
cor(medv,lstat)
cor(lstat, medv) #cor ko phân biệt x, y

# cor = 0: Không có mối quan hệ tuyến tính giữa 2 biến, nhưng có thể tồn tại 
#qh phi tuyến
# cor < 0: hai biến có mối quan hệ tuyến tính âm, khi x tăng -> y giảm
# cor > 0: hai biến có mối quan hệ tuyến tính dương, x tăng y tăng
# cor càng gần 1: mối quan hệ càng mạnh


# Bài toán kiểm định hệ số tương quan lý thuyết
cor.test(medv, lstat) 
# r0 (hệ số tương quan mẫu) giữa hai biến medv, lstat

#Bài toán:
#H0: ro = 0 
#H1: ro!= 0

# Do p-value < 2.2e-16 < 0.05 nên bác bỏ H0
# KL: Với myn 5% có thể nói có có mối tương quan tuyến tính giữa lstat và medv
# Khi đó ta xây dựng mô hình hồi quy tuyến tính của medv theo lstat 
#hoặc lstat theo medv

# Mô hình Hồi quy tuyến tính của medv theo lstat: 
# medv = a0 + a1 * last
#C1:
(lmfit = lm(medv ~ lstat + 0)) # medv = a1 * lstat (a0 = 0)
(lmfit = lm(medv ~ lstat)) # Cách 1: sử dụng sau khi attach data, a0 != 0
#C2:
# Đây là mô hình thường dùng
(lmfit = lm(medv ~ lstat, data = Boston))
#C3:
(lmfit = lm(Boston$medv ~ Boston$lstat))
#C2 va C3 khong can attach

```

## Đánh giá sự phù hợp của mô hình:

```{r}

# Để đánh giá sự phù hợp của mô hình nhiều tiêu chí
# Ở đây chúng ta xem xét:
# 1. Hệ số a0, a1 trong mô hình có thực sự khác 0
# 2. Phân dư: e = medv (thực tế) - medv (mô hình) có tuân theo phân phối chuẩn với giá trị trung bình = 0 hay không ?

summary(lmfit) # tóm tắt kết quả của lmfit

# Xây dựng mô hình HQTT của medv theo lstat trong bộ dữ liệu Boston
# Phần dư: ...
# Hệ số a0 và a1
# UL của hệ số a0 là a0 (intercept) = 34.55384, UL của hệ số a1 là a1 = -0.95005

# Phương trình đường thẳng HQTT biểu diễn medv theo lstat là:
#   medv = 34.55384 - 0.95005 * lstat

# Sai số tiêu chuẩn
# t value và Pr(>|t|) lần lượt là test thống kê và p-value trong bài toán kiểm định hệ số của mô hình

# Bài toán 1: H0: a0 = 0 vs H1: a0 != 0
# do p-value < <2e-16 < 0.05 nên bác bỏ H0
# KL: với myn 5%, có cơ sở để nói hệ số a0 khác 0

# Bài toán 2: H0: a1 = 0 vs a1 != 0
# do p-value < <2e-16 < 0.05 nên bác bỏ H0
# KL: với myn 5%, có cơ sở để nói hệ số a1 khác 0

# hay biến lstat có ý nghĩa thống kê


```

## Phần dư của mô hình:

```{r}
e = lmfit$residuals # Phần dư của mô hình
# Kiểm định xem e có tuân theo phân phối chuẩn với giá trị trung bình bằng 0 không
shapiro.test(e)

# Bài toán: H0: e tuân theo PP chuẩn
#            H1: e không tuân theo PP chuẩn
# Do p-value < 2.2e-16 > 0.05 nên bác bỏ H0
# KL: với myn 5%, e không tuân theo pp chuẩn

wilcox.test(e)
# Bài toán : H): E(e) = 0 vs H1: E(e) != 0
# do p-value = 0.0002031 < 0.05 nên bác bỏ H0
# KL : e có GTTB != 0

# Trong mô hình hồi quy tuyến tính người ta luôn giả định rằng: E(e) = 0 chính vậy mình cần kiểm tra
# Mô hình hồi quy tuyến tính cơ banr là: y = a0 + a1 * x + e


plot(fitted(lmfit),e, xlab = "Fitted values",
     ylab = "Residuals",
     main = "Residuals Plot")


abline(h = 0, col = "red") 
# Lệnh abline này phải chạy cùng với lệnh plot thì mới hoạt đột 
```

## Ước lượng khoảng tin cậy:

```{r}
lmfit <- lm(medv ~ lstat, data = Boston)
newdata <- data.frame(lstat = c(5,10,15))
newdata
#Khoảng tin cậy 90% cho a0 và a1
confint(lmfit, level = 0.9)

#KTC 95% cho GTTB của medv với lstat cho trước
predict(lmfit, newdata = newdata,
        interval = "confidence", level = 0.95)

#Khoảng dự đoán cho giá trụ thực của medv với lstat cho trước
predict(lmfit, data.frame(lstat = c(5,10,15)),
        interval = "prediction", level = 0.95)
```

## Chia tập dữ liệu train test:

### 1. Chia bộ dữ liệu {(x_i, u_i)} ban đầu thành 2 tập con:

```{r}
# training set và testing set
# lấy ngẫu nhiên một tập dữ liệu con (theo tỷ lệ cho trước) để làm training set và phân dữ liệu còn lại dùng làm testing set
```

### 2. Xử lý traning set: Xây dựng mô hình hồi quy lý thuyết:

```{r}

# Xử lý training set: xây dựng mô hình hồi quy lý thuyết
# y = alpha_0 + alpha_1 * x + e
# i, đưa ra ước lượng của hệ số hồi quy: alpha_0_h và alpha1_h
# Phương trình đừng thẳng hồi quy: y = alpha_0_h + alpha_1_h * x
### Đưa ra khoảng tin cậy beta = 95% cho hệ số hồi quy alpha_0 và alpha_1

# Khoảng tin cậy beta = 95% cho hệ số hồi quy alpha_0 và alpha_1
#-> KTC beta cho alpha0 là (a,b), tức là: 
# P(a< alpha0 < b) = beta
# ii, Kiểm định / Đánh giá các hệ số hồi quy tức la kiem dinh bai toan:
### h0: alpha_i = 0 voiw h1: alpha_i != 0
# iii, Kiểm định phần dư có tuân theo pp chuẩn với giá trị trung bình băng 0 không

#3. Đánh giá mô hình trên dựa vào testing set:
# Tính TSS = sum((y-mean(y))^2)
# - Tính RSS  = sum(e ^ 2) = sum((y - yh) ^ 2)
# trong do y_h = alpah_0_h + alpha_1_h * x
# Tính R^2 = 1 - RSS/TSS : Hệ số xác định
### R^2: càng lớn thì ước lượng của a0, a1 càng tốt

```

```{r}

data(iris)
#1. Chia bộ dữ liệu iris thành 2 phần:
set.seed(1)
# Use 70% of dataset as tranining set and remaining 30% as testing set
sample = sample(c(T, F), nrow(iris), replace = T, prob = c(0.7, 0.3))

## Sinh ra 1 vecto ngẫu nhiêu gồm n quan sát (n = nrow(iris) giá trị = số hàng của mỗi cột)
## các giá trị của mẫu sample là true hoặc false
## tham số replace = true tức là các giá trị true, false có thể lặp lại nhiều lần
## tham số prob = c(.7, .3) tuwccs là 70% giá trị của mẫu sample là true, 30% là false

table(sample)

train = iris[sample, ] # gồm 70% quan sát của bộ dữ liệu iris, lấy dữ liệu ở các quan sát
# Có vị trí sao cho tại đó sasmple = T
train
View(train)
test= iris[!sample, ] # gồm 30% quan sát còn lại

# iris: Xây dựng mô hình Hqtt của sepal.length(y) theo petal.length(x): làm ý 2, 3
```

```{r}

# Bài 2:
# i, đưa ra ước lượng của hệ số hồi quy: alpha_0_h và alpha1_h
# Phương trình đừng thẳng hồi quy: y = alpha_0_h + alpha_1_h * x
### Đưa ra khoảng tin cậy beta = 95% cho hệ số hồi quy alpha_0 và alpha_1

# Khoảng tin cậy beta = 95% cho hệ số hồi quy alpha_0 và alpha_1
#-> KTC beta cho alpha0 là (a,b), tức là: 
# P(a< alpha0 < b) = beta
# ii, Kiểm định / Đánh giá các hệ số hồi quy tức la kiem dinh bai toan:
### h0: alpha_i = 0 voiw h1: alpha_i != 0
# iii, Kiểm định phần dư có tuân theo pp chuẩn với giá trị trung bình băng 0 không

lmfit2 = lm(train$Sepal.Length ~ train$Petal.Length) #Mô hình hồi quy tuyến tính
summary(lmfit2) # hàm tóm tắt thông tin
# a0 = 4.28040, a1 =  0.41055
# PTDT HQTT Sepal length theo petal length là 
# Sepal.length = 4.2804 + 0.41055 * Petal.length

confint(lmfit2, level = 0.95)
# Khoảng tin 95% cho a0 là (4.081236, 4.4795609)
# Khoảng tin cậy 95% cho a1 là (0.362601, 0.4584977)

# Bài toán 1: H0: a0 = 0 vs H1: a0 != 0 (Dùng bảng summary)
# do p-value < <2e-16 < 0.05 nên bác bỏ H0
# KL: với myn 5%, có cơ sở để nói hệ số a0 khác 0

# Bài toán 2: H0: a1 = 0 vs a1 != 0 (Dùng bảng summary)
# do p-value < <2e-16 < 0.05 nên bác bỏ H0
# KL: với myn 5%, có cơ sở để nói hệ số a1 khác 0

# nghĩa là biến Petal.Length có ý nghĩa thống kê

# Phần dư mô hình
e = lmfit2$residuals
shapiro.test(e) 
#Bài toán: 
#H0: e tuân theo PP chuẩn
#H1: e không tuân theo pp chuẩn
# do p-value = 0.8481 > 0.05 nên chấp nhận H0
# KL: với MYN 5%, ta có thể nói e tuân theo PP chuẩn


t.test(e, mu = 0) # Do e tuân theo phân phối chuẩn
# Bài toán: 
# H0: E(e) = 0  # Kì vọng của biến ngẫu nhiên e
# H1: E(e) != 0
# Do p-value = 1 > 0.05 nên ta chấp nhận H0
# KL: với MYN 5%, ta có thể nói kỳ vọng của e = 0

plot(e)
abline(h = 0, col = "red")
```

```{r}
# Bài 3:
#3. Đánh giá mô hình trên dựa vào testing set:
# Tính TSS = sum((y-mean(y))^2)
# - Tính RSS  = sum(e ^ 2) = sum((y - yh) ^ 2)
# trong do y_h = alpah_0_h + alpha_1_h * x
# Tính R^2 = 1 - RSS/TSS : Hệ số xác định
### R^2: càng lớn thì ước lượng của a0, a1 càng tốt

y = test$Sepal.Length
x = test$Petal.Length
TSS <- sum((y - mean(y))^2)
a0 = 4.28040
a1 = 0.41055
yh = a0 + a1 * x  #Do mình đã xác định được E(e) = 0
RSS <- sum((y - yh)^2)
r2 = 1 - RSS/TSS
r2



```
